#ifndef CAN_DIAG_CFG_H
#define CAN_DIAG_CFG_H
#define CANDIAG_PERIOD_MS 10u
#define CANDIAG_BMS_PDU 0u
#define CANDIAG_RX_TIMEOUT_MS 100u
#define CANDIAG_TX_TIMEOUT_MS 50u
#define CANDIAG_NM_TIMEOUT_MS 300u
#define CANDIAG_BUSOFF_RECOVERY_MS 100u
#endif
