function build_TireMagicFormula_Simulink()
%BUILD_TIREMAGICFORMULA_SIMULINK
% Programmatically creates a MATLAB R2025b Simulink model:
%   TireMagicFormula_R2025b.slx
%
% Inputs:
%   Kappa [-]
%   Alpha [rad]
%   Fz [N]
%
% Outputs:
%   Fx [N]
%   Fy [N]
%   MuX [-]
%   MuY [-]
%
% The central calculation is implemented in a MATLAB Function block.

mdl = 'TireMagicFormula_R2025b';

if bdIsLoaded(mdl)
    close_system(mdl,0);
end

if isfile([mdl '.slx'])
    delete([mdl '.slx']);
end

new_system(mdl);
open_system(mdl);

set_param(mdl,'Solver','FixedStepDiscrete', ...
               'FixedStep','0.001', ...
               'StopTime','5');

% Inports
add_block('simulink/Sources/In1',[mdl '/Kappa'], ...
    'Position',[40 60 90 90]);
add_block('simulink/Sources/In1',[mdl '/Alpha_rad'], ...
    'Position',[40 130 90 160]);
add_block('simulink/Sources/In1',[mdl '/Fz_N'], ...
    'Position',[40 200 90 230]);

set_param([mdl '/Kappa'],'Port','1');
set_param([mdl '/Alpha_rad'],'Port','2');
set_param([mdl '/Fz_N'],'Port','3');

% MATLAB Function block
mf = add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [mdl '/MagicFormula'], ...
    'Position',[220 65 470 235]);

% Set MATLAB Function source.
rt = sfroot;
chart = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/MagicFormula']);

code = sprintf([ ...
'function [Fx,Fy,muX,muY] = fcn(kappa,alpha,Fz)\n' ...
'%%#codegen\n' ...
'Fz = max(Fz,0);\n' ...
'Fz0 = 4000.0;\n' ...
'Bx = 10.0; Cx = 1.65; Ex = 0.97; muX0 = 1.05;\n' ...
'By = 7.0;  Cy = 1.30; Ey = -1.60; muY0 = 1.00;\n' ...
'muLoadX = -0.08; muLoadY = -0.10;\n' ...
'lr = max(Fz/Fz0,1e-6);\n' ...
'muX = muX0*lr^muLoadX;\n' ...
'muY = muY0*lr^muLoadY;\n' ...
'Dx = muX*Fz;\n' ...
'Dy = muY*Fz;\n' ...
'\n' ...
'zx = kappa;\n' ...
'Bxz = Bx*zx;\n' ...
'Fx0 = Dx*sin(Cx*atan(Bxz-Ex*(Bxz-atan(Bxz))));\n' ...
'\n' ...
'zy = alpha;\n' ...
'Byz = By*zy;\n' ...
'Fy0 = Dy*sin(Cy*atan(Byz-Ey*(Byz-atan(Byz))));\n' ...
'\n' ...
'nx = Fx0/max(abs(Dx),1e-9);\n' ...
'ny = Fy0/max(abs(Dy),1e-9);\n' ...
'normF = sqrt(nx*nx + ny*ny);\n' ...
'scale = 1.0;\n' ...
'if normF > 1.0\n' ...
'    scale = 1.0/normF;\n' ...
'end\n' ...
'Fx = Fx0*scale;\n' ...
'Fy = Fy0*scale;\n' ...
'end\n']);

chart.Script = code;

% Outports
add_block('simulink/Sinks/Out1',[mdl '/Fx_N'], ...
    'Position',[580 65 630 95]);
add_block('simulink/Sinks/Out1',[mdl '/Fy_N'], ...
    'Position',[580 115 630 145]);
add_block('simulink/Sinks/Out1',[mdl '/MuX'], ...
    'Position',[580 165 630 195]);
add_block('simulink/Sinks/Out1',[mdl '/MuY'], ...
    'Position',[580 215 630 245]);

% Wiring
add_line(mdl,'Kappa/1','MagicFormula/1');
add_line(mdl,'Alpha_rad/1','MagicFormula/2');
add_line(mdl,'Fz_N/1','MagicFormula/3');

add_line(mdl,'MagicFormula/1','Fx_N/1');
add_line(mdl,'MagicFormula/2','Fy_N/1');
add_line(mdl,'MagicFormula/3','MuX/1');
add_line(mdl,'MagicFormula/4','MuY/1');

% Documentation blocks
add_block('simulink/Signal Routing/Goto',[mdl '/Doc_Goto'], ...
    'Position',[760 80 820 110], 'GotoTag','MF_Documentation');
delete_block([mdl '/Doc_Goto']);

save_system(mdl,[mdl '.slx']);
open_system(mdl);

fprintf('Created: %s.slx\n',mdl);
fprintf('Inputs : Kappa, Alpha_rad, Fz_N\n');
fprintf('Outputs: Fx_N, Fy_N, MuX, MuY\n');
end
